[[language]]
name = "php"
scope = "source.php"
injection-regex = "php"
file-types = ["php",]
shebangs = ["php"]
roots = ["composer.json", "index.php"]
language-servers = ["intelephense"]
indent = { tab-width = 4, unit = "    " }

[language-server.intelephense]
command = "intelephense"
args = ["--stdio"]

[[grammar]]
name = "php"
source = { git = "https://github.com/tree-sitter/tree-sitter-php", rev = "f860e598194f4a71747f91789bf536b393ad4a56" }
