---
- hosts: all

  vars_files:
    - config.yml

  roles:
    - role: dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: config
      when: configure_config
      tags: ['config']
    - role: homebrew
      when: configure_homebrew
      tags: ['homebrew']
    - role: composer
      when: configure_composer
      tags: ['composer']
