---
- name: Ensuring Homebrew Is Installed
  stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check

- name: Installing Homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when:
    - not homebrew_check.stat.exists

- name: Updating Homebrew
  homebrew:
    update_homebrew: true
  when: homebrew_check.stat.exists

- name: Ensure configured taps are tapped.
  homebrew_tap:
   tap: '{{ item.name | default(item) }}'
   url: '{{ item.url | default(omit) }}'
   state: present
  loop: "{{ homebrew_taps }}"

- name: Installing Homebrew Packages
  homebrew:
    name: "{{ item }}"
    state: present
  register: result
  loop: "{{ homebrew_apps }}"
  until: result is successful
  when: homebrew_check.stat.exists

- name: Upgrading Homebrew Packages
  homebrew: update_homebrew=yes upgrade_all=yes
  register: result
  until: result is successful
  when: homebrew_check.stat.exists

- name: Installing Homebrew Cask Packages
  homebrew_cask:
    name: "{{ item }}"
    state: latest
  loop: "{{ homebrew_casks }}"
  register: result
  until: result is successful
  when: homebrew_check.stat.exists
